### ISSUE TITLE
user-can-view-all-shoes

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can view all shoe products

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click 'Shop Now' link to go to the product's page. 
It will take the user to the 'Shop All Sneakers' page to scroll through all pairs of shoes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-01-03 at 12 47 17 AM](https://user-images.githubusercontent.com/113474457/210324718-21cbe9d3-2fcc-48d4-8bec-1b0ee099d303.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create a database of all of the available shoe products and their sizes
- [x] Update `schema.sql` to have the shoe product's information table
- [x] Update `data.sql` to hold the data of all the shoe product information
- [x] Ensure to perform `npm run db:import` to import all `data.sql`
- [x] Give a name to your database

### ☁️ Server Tasks

- [x] Update `server/index.js` to get all shoe's data from the database using `app.get` method
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a `NavBar` component
- [x] Create a `home` page that would hold a background page with the `NavBar` 
- [x] Ensure the` store` icon takes the user to the 'Shop All Sneakers' page
- [x] Ensure the user can return to `home` page when icon is clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out codes.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
