### ISSUE TITLE
user-can-search-for-a-product

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the `search icon` to search a product

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on the `search icon` to have the modal come out from the right side. 
Users can start typing on the search bar and click the search icon inside the search form or press `Enter` to search
      - products should show up inside the modal as soon as the user searches for a shoes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:
![Screenshot 2023-01-16 at 9 50 11 PM](https://user-images.githubusercontent.com/113474457/212819939-f6ace95f-9a05-48d8-a680-c280475ded5c.png)

Desktop:
![Screenshot 2023-01-16 at 9 50 46 PM](https://user-images.githubusercontent.com/113474457/212820026-494785f2-75af-4847-8dcc-561f6fcf7745.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] No changes needed

### ⚡ Client Tasks

- [x] Create a function that filters through the database of `products` depending on what the user is searching for on the search bar
- [x] Create a modal that pops up once the user clicks on the `search` `icon` on the Navigation bar

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
