### ISSUE TITLE
user-can-check-out-a-product

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can place an order for the items they have added to their cart

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. Once the user clicks on the 'GO TO CHECKOUT' `button`, it will take the user to the `checkout` page
2. Have a shipping address form, click the NEXT `button` to go to the payment information page. 
3.  Create a payment form page and once the user clicks, the 'PLACE ORDER' `button`, if the payment goes through, it will take the user to the confirmation page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Mobile:**
![Screenshot 2023-01-08 at 9 01 08 PM](https://user-images.githubusercontent.com/113474457/211243668-e9c1d158-5c2a-4b43-95fd-30cc759ce263.png)

**Desktop**
![Screenshot 2023-01-08 at 9 01 40 PM](https://user-images.githubusercontent.com/113474457/211243723-b6870d73-8518-43f8-8b83-77ac110750e9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] No changes

### ☁️ Server Tasks

- [x] update `server/index.js` to `POST` when checking out. Need to insert into `usersAddress` database while updating the `orders` & `cart` database
- [x] Update 'server/index.js` to `GET` to calculate the total cost of the cart
- [x] Update `index.js` to `POST` to `/create-payment-intent`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component that holds the checkout form with `shipping address` & `payment form`
- [x] Implement STRIPE API to take payment
- [x] Create a page that takes the user to the confirmation page once payment has been successful

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
