### ISSUE TITLE
user-can-delete-a-product-from-the-cart

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete the product(s) from their current cart 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User can click on the trash can `icon` to delete the item from the cart

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Mobile:**
<img width="735" alt="Screenshot 2023-01-07 at 2 20 12 PM" src="https://user-images.githubusercontent.com/113474457/211172384-a6432566-4216-4040-8f2f-36b41b76388a.png">
**Desktop:**
<img width="1041" alt="Screenshot 2023-01-07 at 2 20 51 PM" src="https://user-images.githubusercontent.com/113474457/211172399-ae3a5d98-fb52-46d0-b13d-15db237cf17c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] No need to update the database

### ☁️ Server Tasks

- [x] Update `server/index.js` to `delete` from `cartItems` & `cart` database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a method inside the `cart.jsx` to be able to delete the item from the cart
- [x] Use `IconButton` from Material UI and trash `icon` 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
