### ISSUE TITLE
user-can-view-current-cart

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their current cart
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. There will be two different ways for the user to view their cart
        a. When the user clicks to add an item to the cart, the user may click the 'GO TO CART' `Button` to view their cart
        b. Second way to view the cart will be to click on the `Shopping Bag` `icon`

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-01-06 at 11 11 41 AM](https://user-images.githubusercontent.com/113474457/211082778-b46d98e9-f8ae-4a06-9ba6-46707ebf6640.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

No need to update any database for `data.sql` & `schema.sql`.

### ☁️ Server Tasks

- [x] Update `server/index.js` to  `get` the cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the `GO TO CART` `button` hash routing in the app component to display the cart view
- [x] Create a `Cart` page component to display the cart page 

- [x] Create a fetch request that includes the token to grab all the items in the cart
- [x] Items in the cart should have `name`, `size`, `image`, `price`, and `quantity`
- [x] Create a Summary section to display: `Subtotal`, `Shipping`, `Estimated Tax`, and `Total`.
- [x] If the user has no products in the cart, display 'Your cart is currently empty!` & a `button` to take the user to the 'Shop All Sneakers' page. 

         

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out codes.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
