### ISSUE TITLE
user-can-add-a-product-to-cart

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add a product to their cart
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able to click on the 'ADD TO CART' `button` in order to add the `SKU` & `size` to the cart

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2023-01-05 at 4 11 26 PM](https://user-images.githubusercontent.com/113474457/210903775-4b643986-802f-444e-a577-607b320babca.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] No need to update the database

### ☁️ Server Tasks

- [x] Update `server/index.js` to `post` in order to add the product to the cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display a modal to display the current cart once the user clicks the 'ADD TO CART' `button`. 
- [x] Update `ShoppingBagIcon` in the `NavBar` component to display the `Cart` modal once clicked

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out codes.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
