### ISSUE TITLE
user-can-click-a-product-to-view-product

### ISSUE THREAD

**Issue by josephswpark** [josephswpark/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click a product to view each product.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user clicks a product's image or name, the user can view detailed information of the specific product. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-01-03 at 10 02 16 AM](https://user-images.githubusercontent.com/113474457/210414919-c2fdf52b-b609-4943-8c88-a02aba158e20.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] No need to update database for this feature

### ☁️ Server Tasks

- [x] Update `server/index.js` to get the `productId` and its `size`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a page of `product-details` to show each product's information
- [x] The product page should include: `sizes`, `image`, `name`,  `sku`, and 'add to cart' `button`

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
